version: '2.1'

orbs:
  snyk: snyk/snyk@1.2.3

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Install Xvfb
          command: sudo apt-get install -y xvfb
      - run:
          name: Run Cypress Tests
          command: npm run test:ci
      - snyk/install

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
