version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  build-docker-image:
    docker:
      - image: cimg/node:12.22  # Updated to Node.js 12
    environment:
      DOCKER_IMAGE: nodegoat
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_IMAGE:latest .
      - run:
          name: Install Snyk to HTML
          command: npm install --prefix=$HOME/.local -g snyk-to-html

  snyk-scan:
    docker:
      - image: cimg/node:12.22  # Updated to Node.js 12
    steps:
      - checkout
      - run:
          name: Install Snyk to HTML
          command: npm install --prefix=$HOME/.local -g snyk-to-html
      - snyk/scan:
          monitor-on-build: false
          fail-on-issues: false
          command: container test $DOCKER_IMAGE
          additional-arguments: --json-file-output=code-results.json
      - run:
          name: Generate Snyk HTML report
          command: cat code-results.json | snyk-to-html -o code-report.html
      - store_artifacts:
          path: code-report.html

workflows:
  build-test-snyk:
    jobs:
      - build-docker-image
      - snyk-scan:
          requires:
            - build-docker-image
