version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  build-docker-image-and-snyk-scan:
    docker:
      - image: cimg/node:12.22  # Updated to Node.js 12
    environment:
      DOCKER_IMAGE: nodegoat
    steps:
      - checkout
      - run:
          name: Install Snyk CLI
          command: npm install -g snyk
      - run:
          name: Install Snyk to HTML
          command: npm install --prefix=$HOME/.local -g snyk-to-html    
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_IMAGE:latest .
            snyk container test $DOCKER_IMAGE:latest  --json | tee snyk-results.json
      - run:
          name: Generate Snyk HTML report
          command: cat snyk-results.json | snyk-to-html -o snyk-report.html
      - store_artifacts:
          path: snyk-report.html

workflows:
  build-test-snyk:
    jobs:
      - build-docker-image-and-snyk-scan
