version: 2.1

jobs:
  snyk-scan:
  build:
    machine:
      image: ubuntu-2204:2024.04.4
    working_directory: /tmp
    steps:
      - checkout # Check out the code in the project directory
      - run:
          name: Install nvm and Node.js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18.17.0
            nvm use 18.17.0
            nvm alias default 18.17.0
            node -v
            npm -v
      - run:
          name: Install npm@latest
          command: npm install -g npm@latest
      - run:
          name: Install Snyk
          command: |
            curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
            chmod +x ./snyk
            sudo mv ./snyk /usr/local/bin/
      - run:
          name: Authenticate Snyk
          command: snyk auth $SNYK_TOKEN
      - run:
          name: Install snyk-to-html
          command: npm install snyk-to-html -g
      - run:
          name: Generate Snyk Report
          command: snyk code test --json-file-output=results-code.json
      - run:
          name: Convert Snyk Report to HTML
          command: snyk-to-html -i results-code.json -o /tmp/results-code.html
      - store_artifacts:
          path: /tmp/results-code.html
          destination: artifact-file
workflows:
  my-workflow:
    jobs:
      - snyk-scan
