version: 2.1

workflows:
  version: 2
  main_workflow:
    jobs:
      - code_scan
      - sca
      - container_scan
      - secret_scan

jobs:
  code_scan:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run Code Scan
          command: |
            circleci config process .circleci/code_scan_config.yml > .circleci/code_scan_processed.yml
            circleci local execute -c .circleci/code_scan_processed.yml --job build

  sca:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run SCA
          command: |
            circleci config process .circleci/sca_config.yml > .circleci/sca_processed.yml
            circleci local execute -c .circleci/sca_processed.yml --job build

  container_scan:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run Container Scan
          command: |
            circleci config process .circleci/container_config.yml > .circleci/container_processed.yml
            circleci local execute -c .circleci/container_processed.yml --job build

  secret_scan:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run Secret Scan
          command: |
            circleci config process .circleci/secret_scan_config.yml > .circleci/secret_scan_processed.yml
            circleci local execute -c .circleci/secret_scan_processed.yml --job build
