version: 2.1

jobs:
  sonar-analysis:
    docker:
      - image: sonarsource/sonar-scanner-cli

    steps:
      - checkout

      # Run SonarQube Scanner
      - run:
          name: Run SonarQube Scanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=NodeGoat102 \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://65.1.31.213:9000 \
              -Dsonar.token=sqp_069cf4ee1673a0158bbbd8ec263a09cd388d03f2

workflows:
  build-and-analyze:
    jobs:
      - sonar-analysis
