version: 2.1

orbs:
  sonarscanner: psl/sonarscanner@0.0.4  # Update orb version if needed

jobs:
  sonar-analysis:
    docker:
      - image: circleci/openjdk:11.0  # Replace with the image for your project

    steps:
      - checkout

      # Run SonarScanner to perform analysis
      - sonarscanner/scan:
          sonar-login: sqa_7133fba4d5ef09560130e30ce3e1e23a39d26823
          sonar-host-url: http://65.1.31.213:9000/
          sonar-project-key: Test
          sonar-sources: . 

workflows:
  build-and-analyze:
    jobs:
      - sonar-analysis:
          filters:
            branches:
              only: main
