version: 2.1

jobs:
  sonar-analysis:
    docker:
      - image: ubuntu

    steps:
      - checkout

      # Install Docker
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io

      # Pull SonarQube Docker image
      - run:
          name: Pull SonarQube Docker image
          command: |
            docker pull sonarsource/sonar-scanner-cli:latest

      # Run SonarQube analysis using Docker
      - run:
          name: Run SonarQube analysis
          command: |
            docker run \
              --rm \
              -v "${PWD}:/usr/src" \
              -e SONAR_HOST_URL=http://65.1.31.213:9000/ \
              -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=NodeGoat" \
              -e SONAR_TOKEN=$SONAR_TOKEN \
              sonarsource/sonar-scanner-cli

workflows:
  build-and-analyze:
    jobs:
      - sonar-analysis
