version: 2.1

orbs:
  sonarqube: sonarsource/sonarqube@1.0.2  # Updated orb

jobs:
  sonar-analysis:
    docker:
      - image: circleci/openjdk:11.0  # Replace with the image for your project

    steps:
      - checkout

      # Run SonarScanner to perform analysis
      - sonarqube/scan:
          organization: your-organization
          projectKey: Test
          sonarHostUrl: http://65.1.31.213:9000/
          sonarToken: sqa_7133fba4d5ef09560130e30ce3e1e23a39d26823
          sources: "."

workflows:
  build-and-analyze:
    jobs:
      - sonar-analysis:
          filters:
            branches:
              only: main
