version: 2.1

jobs:
  sonar-analysis:
    docker:
      - image: circleci/openjdk:11.0  # Use the Java Docker image for running SonarScanner

    steps:
      - checkout

      # Setup Docker
      - setup_remote_docker:
          version: 20.10.7  # Specify the Docker version to use

      # Pull SonarQube Scanner Docker image
      - run:
          name: Pull SonarQube Scanner Docker image
          command: |
            docker pull sonarsource/sonar-scanner-cli:latest

      # Display current directory
      - run:
          name: Show current directory
          command: |
            pwd
            ls -l

      # Run SonarQube Scanner
      - run:
          name: Run SonarQube Scanner
          command: |
            docker run \
              --rm \
              -v "${PWD}:/usr/src" \
              -e SONAR_HOST_URL=http://65.1.31.213:9000/ \
              -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=NodeGoat" \
              -e SONAR_TOKEN=$SONAR_TOKEN \
              sonarsource/sonar-scanner-cli:latest

workflows:
  build-and-analyze:
    jobs:
      - sonar-analysis
