version: 2.1

jobs:
  snyk-scan:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout # Check out the code in the project directory
      - run:
          name: Install Node.js and npm
          command: |
            sudo apt-get update
            sudo apt-get install -y nodejs npm
            sudo npm install -g npm@latest
      - run:
          name: Install Snyk
          command: |
            curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
            chmod +x ./snyk
            sudo mv ./snyk /usr/local/bin/
      - run:
          name: Authenticate Snyk
          command: snyk auth $SNYK_TOKEN
      - run:
          name: Install snyk-to-html
          command: npm install snyk-to-html -g
      - run:
          name: Generate Snyk Report
          command: snyk test --json > snyk-report.json
      - run:
          name: Convert Snyk Report to HTML
          command: snyk-to-html -i snyk-report.json -o snyk-report.html
      - run:
          name: Save artifacts
          command: mkdir -p /tmp/artifacts && cp snyk-report.html /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifacts
workflows:
  my-workflow:
    jobs:
      - snyk-scan
