version: 2.1

jobs:
  sonar-analysis:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Use the SonarScanner CLI Docker image
    steps:
      - checkout

      # Run SonarQube analysis using Docker
      - run:
          name: Run SonarQube analysis
          command: |
            sudo docker run \
              --rm \
              -v "${PWD}:/usr/src" \
              --network="host" \
              -e SONAR_HOST_URL="http://65.1.31.213:9000/" \
              -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=Test" \
              -e SONAR_TOKEN="sqa_7133fba4d5ef09560130e30ce3e1e23a39d26823" \
              sonarsource/sonar-scanner-cli

workflows:
  build-and-analyze:
    jobs:
      - sonar-analysis:
          filters:
            branches:
              only: main
