version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
  snyk-scan:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - run:
          name: Install Snyk to HTML
          command: npm install --prefix=$HOME/.local -g snyk-to-html
      - snyk/scan:
          monitor-on-build: false
          fail-on-issues: false
          command: test
          additional-arguments: --json-file-output=dependency-results.json
      - run:
          name: Generate Snyk HTML report
          command: cat dependency-results.json | snyk-to-html -o dependency-report.html
      - store_artifacts:
          path: dependency-report.html

workflows:
  build-test-snyk:
    jobs:
      - build-and-test
      - snyk-scan
