name: Pipeline Example With 2MS

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run 2ms Scan
        run: |
          docker run -v $(pwd):/repo checkmarx/2ms:2.8.1 git /repo > 2ms_results.txt
          cat 2ms_results.txt

          # Optional: fail if HIGH severity issues are found
          if grep -q "HIGH" 2ms_results.txt; then
            echo "❌ High severity issues found!"
            exit 1
          else
            echo "✅ No high severity issues found."
          fi
