name: BlackDuck-CI-Coverity # Name of the workflow
on:
  push:  # Trigger the workflow on push events
    branches: [main, master, develop, stage, release]  # Specify branches to trigger on push
  pull_request:  # Trigger the workflow on pull request events
    branches: [main, master, develop, stage, release]  # Specify branches to trigger on PR

jobs:
  build:  # Define a job named 'build'
    runs-on: [sh_mac_mdn]  # Specify the runner to execute the job
    steps:  # List of steps to execute in this job
      - name: Checkout Source  # Step to check out the repository code
        uses: actions/checkout@v4 # Use the checkout action to clone the repo
      - name: Black Duck Coverity Scan  # Step for running a full CNC Scan
        uses: blackduck-inc/black-duck-security-scan@v2  # Use the Black Duck security scan action
        with:
         ### SCANNING: Required fields
          coverity_url: ${{ secrets.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          coverity_project_name: "MDN_Coverity_Aug17"
          coverity_stream_name:  "MDN_Coverity_Aug17"
         ### POLICY ENFORCEMENT: Uncomment to break build on policy
          coverity_policy_view: 'Outstanding Issues' 

        ### PULL REQUEST COMMENTS:
          coverity_prComment_enabled: true
          github_token: ${{ secrets.BD_GITHUB_TOKEN }}  # Black Duck API token from secrets

         ### Mark build status if policy violating issues are found
        #mark_build_status: 'success'
          