name: "CodeQL Analysis"

on:
  push:
    branches: [main]  # Scan on pushes to the main branch
  pull_request:
    # Scan on pull requests targeting the main branch
    branches: [main]
  schedule:
    # Schedule a daily scan at 2:00 AM
    - cron: '0 2 * * *'

jobs:
  analyze:
    name: "Run CodeQL Analysis"
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'python', 'go', 'typescript', 'java', 'cpp' ]  # Add/remove languages based on your project

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Initialize CodeQL"
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: "Perform CodeQL Analysis"
        uses: github/codeql-action/analyze@v2
        with:
          category: "security"
