name: Dependabot Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependabot-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for Critical and High Vulnerabilities
        run: |
          echo "Fetching Dependabot alerts..."
          ALERTS=$(curl -s -H "Authorization: token ${{ secrets.GH_SECURITY_TOKEN }}" \
                         -H "Accept: application/vnd.github+json" \
                         https://api.github.com/repos/${{ github.repository }}/dependabot/alerts)
                         
          echo "API Response:"
          echo "$ALERTS"
          
          echo "Generating CSV report..."
          echo "number,state,package,ecosystem,manifest_path,severity,summary,created_at,url" > dependabot_report.csv
          
          # Generate CSV only for open alerts
          echo "$ALERTS" | jq -r '.[] | select(.state == "open") | [
              .number,
              .state,
              .dependency.package.name,
              .dependency.package.ecosystem,
              .dependency.manifest_path,
              .security_advisory.severity,
              .security_advisory.summary,
              .created_at,
              .html_url
            ] | @csv' >> dependabot_report.csv

          # Count open critical and high alerts
          CRITICAL_ALERTS=$(echo "$ALERTS" | jq '[.[] | select(.state == "open" and .security_advisory.severity == "critical")] | length')
          HIGH_ALERTS=$(echo "$ALERTS" | jq '[.[] | select(.state == "open" and .security_advisory.severity == "high")] | length')

          if [ "$CRITICAL_ALERTS" -gt 0 ] || [ "$HIGH_ALERTS" -gt 0 ]; then
            echo "Critical or high severity open alerts detected."
            echo "Failing build due to $CRITICAL_ALERTS critical and $HIGH_ALERTS high severity open alerts."
            exit 1
          else
            echo "No critical or high severity open Dependabot alerts found."
          fi
          
      - name: Upload CSV Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dependabot-report
          path: dependabot_report.csv
