name: Vorpal Code Scan

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

# name: vorpal-reviewdog

on:
  push:
    branches: [master]  # Adjust this to your default branch

jobs:
  vorpal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Vorpal with reviewdog
        uses: checkmarx/vorpal-reviewdog-github-action@v1.0.0
        with:
          source_path: '**/'  # Adjust file patterns as needed
          filter_mode: file
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          fail_on_error: false
